const core = require('@actions/core');
const github = require('@actions/github');
const path = require('path');
const { scanProject } = require('./lib/scanner');
const { parseEnvFiles } = require('./lib/env-parser');
const { analyze } = require('./lib/analyzer');

async function run() {
  try {
    const directory = core.getInput('directory') || '.';
    const envFileInput = core.getInput('env-file');
    const strict = core.getInput('strict') === 'true';
    const shouldComment = core.getInput('comment') !== 'false';
    const failOnMissing = core.getInput('fail-on-missing') !== 'false';

    const dir = path.resolve(directory);
    const envFiles = envFileInput ? envFileInput.split(',').map(f => f.trim()) : [];

    core.info(`🔍 Scanning ${dir} for environment variable references...`);

    const codeRefs = scanProject(dir, []);
    const envVars = parseEnvFiles(dir, envFiles);
    const result = analyze(codeRefs, envVars);

    core.info(`Found ${result.codeVarCount} variables referenced in code`);
    core.info(`Found ${result.envVarCount} variables in env files (${result.envFiles.join(', ') || 'none found'})`);

    // Set outputs
    core.setOutput('missing', result.missing.length);
    core.setOutput('unused', result.unused.length);
    core.setOutput('documented', result.documented.length);

    // Build markdown report
    const report = buildReport(result, strict);

    // Post PR comment if applicable
    if (shouldComment && github.context.payload.pull_request) {
      await postComment(report);
    }

    // Log summary
    core.summary
      .addRaw(report)
      .write();

    // Fail conditions
    if (failOnMissing && result.missing.length > 0) {
      core.setFailed(`Found ${result.missing.length} missing environment variable(s)`);
    } else if (strict && result.unused.length > 0) {
      core.setFailed(`Found ${result.unused.length} unused environment variable(s) (strict mode)`);
    }
  } catch (error) {
    core.setFailed(`env-audit failed: ${error.message}`);
  }
}

function buildReport(result, strict) {
  const lines = [];
  lines.push('## 🔐 Env Audit Report\n');

  if (result.missing.length === 0 && result.unused.length === 0) {
    lines.push('✅ **All environment variables are accounted for!**\n');
  }

  if (result.missing.length > 0) {
    lines.push(`### ❌ Missing Variables (${result.missing.length})\n`);
    lines.push('These variables are referenced in code but not defined in any env file:\n');
    lines.push('| Variable | File | Line | Has Default? |');
    lines.push('|----------|------|------|-------------|');
    for (const m of result.missing) {
      const def = m.hasDefault ? '✅ Yes' : '⚠️ No';
      lines.push(`| \`${m.name}\` | \`${m.file}\` | ${m.line} | ${def} |`);
    }
    lines.push('');
  }

  if (result.unused.length > 0) {
    lines.push(`### ⚠️ Unused Variables (${result.unused.length})\n`);
    lines.push('These variables are defined in env files but never referenced in code:\n');
    lines.push('| Variable | Defined In |');
    lines.push('|----------|-----------|');
    for (const u of result.unused) {
      lines.push(`| \`${u.name}\` | ${u.sources.map(s => `\`${s}\``).join(', ')} |`);
    }
    lines.push('');
  }

  if (result.documented.length > 0) {
    lines.push(`<details><summary>✅ ${result.documented.length} documented variable(s)</summary>\n`);
    for (const d of result.documented) {
      lines.push(`- \`${d.name}\` — ${d.sources?.join(', ') || d.file}`);
    }
    lines.push('\n</details>\n');
  }

  lines.push('---');
  lines.push(`*${result.codeVarCount} code refs · ${result.envVarCount} env vars · ${result.envFiles.length} env file(s) scanned*`);
  lines.push('*Generated by [env-audit](https://github.com/Quinnod345/env-audit-action)*');

  return lines.join('\n');
}

async function postComment(body) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    core.warning('No GITHUB_TOKEN found — skipping PR comment');
    return;
  }

  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;
  const prNumber = github.context.payload.pull_request.number;

  // Find existing comment to update
  const MARKER = '<!-- env-audit-report -->';
  const { data: comments } = await octokit.rest.issues.listComments({
    owner, repo, issue_number: prNumber,
  });

  const existing = comments.find(c => c.body?.includes(MARKER));
  const commentBody = `${MARKER}\n${body}`;

  if (existing) {
    await octokit.rest.issues.updateComment({
      owner, repo, comment_id: existing.id, body: commentBody,
    });
    core.info('Updated existing PR comment');
  } else {
    await octokit.rest.issues.createComment({
      owner, repo, issue_number: prNumber, body: commentBody,
    });
    core.info('Posted PR comment');
  }
}

run();
